#!/bin/sh
#
# dhclient 
#

start() {
	printf "Starting udhcpc: "
	/usr/sbin/udhcpc
	echo "OK"
}
stop() {
	printf "Stopping udhcpc: "
	killall udhcpc
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

